apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: example-app-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/wikibal01/fluxcd101.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: example-app
  namespace: flux-system
spec:
  interval: 5m
  path: "./kubernetes/overlays/dev"
  prune: true
  sourceRef:
    kind: GitRepository
    name: example-app-repo
  validation: client
